spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true

server.port=8081

# Cấu hình ghi log ra file
logging.file.name=logs/application.log
logging.level.root=INFO
logging.level.com.example.jpa=DEBUG
